export class Nettopay {
    userId!:number;
saleDate!:String;
salePoints!:number;
displayUserId!:String;
commition!:number;
dcommition!:number;
userType!:number;
reportingUser!:number;
gameId!:number;
totalWinning!:number;
netPoints!:number;
userName!:String;
balance!:number;
sale!:number;
winning!:number;
cancel!:number;
dcommision!:number;
commision!:number;
lastTicketMinits!:number;
}
